import type { Metadata } from 'next';
import './global.css';
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: [
    {
      path: '../assets/font/Pretendard-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../assets/font/Pretendard-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/font/Pretendard-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/font/Pretendard-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../assets/font/Pretendard-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-pretendard',
  display: 'swap',
});

interface RootLayoutProps {
  children: React.ReactNode;
  loginModal: React.ReactNode;
}

export default function RootLayout({ children, loginModal }: Readonly<RootLayoutProps>) {
  return (
    <html lang='en'>
      <body className={`${pretendard.variable} antialiased`}>
        {loginModal}
        {children}
      </body>
    </html>
  );
}
